# General training configuration
model: "CNN"                # Select model: cnnViT, CNN, CvT
size: 224                   # Image size
batch_size: 16              # Batch size for training
epochs: 50                  # Number of epochs for training

# Data
dataset: "new"
use_mean: 0                 # For dataloader, is use_mean=True, gets mean isd for whole image, if False gets pixelwise isds. 
train_image_dir: "isd-ViT/training_data/training_images_cropped"          # Directory containing training images
isd_map_dir: "isd-ViT/training_data/training_isds_cropped"                # Directory containing isd maps of training images.


# Results pathing
run: "test_run_01"          # Run name for logging and saving checkpoints
save_dir: "isd-ViT/results/test_run_01"  # Explicitly set save directory
start_epoch: 0              # Starting epoch

# Optimizer configuration
optimizer:
  type: "Adam"               # Type of optimizer (e.g., "Adam", "SGD", etc.)
  lr: 0.0002                 # Learning rate
  weight_decay: 0.0001       # Weight decay (L2 regularization)
  betas: [0.5, 0.999]        # Betas parameter for Adam
  # type: "SGD"              # Type of optimizer (e.g., "Adam", "SGD", etc.)
  # lr: 0.0002               # Learning rate
  # weight_decay: 0.0001     # Weight decay (L2 regularization)
  # momentum: null           # Momentum (only used for optimizers like SGD)

# Scheduler configuration (choose one)
scheduler:
  type: "StepLR"            # Type of scheduler ("StepLR", "ReduceLROnPlateau", etc.)
  params:                   # Scheduler-specific parameters
    step_size: 10           # For StepLR
    gamma: 0.1              # For StepLR

# Alternative scheduler configurations (comment out the above and uncomment one of these if needed)
# scheduler:
#   use_scheduler: true
#   type: "ReduceLROnPlateau"
#   params:
#     mode: "min"
#     factor: 0.1
#     patience: 5
#     threshold: 0.01
#     cooldown: 2

# scheduler:
#   use_scheduler: true
#   type: "CosineAnnealingLR"
#   params:
#     T_max: 50
#     eta_min: 1e-6

# Pretrained settings
pretrained:
  checkpoint_path: null     # Path to checkpoint file if loading a previous state
  load_model_state: false   # Whether to load the model state
  load_optim_states: false  # Whether to load optimizer states